from training.train_cifar10 import train_child_cifar10, grid_search_cifar10
from training.train_ptb import train_child_ptb, evaluate_ptb, grid_search_ptb
from training.async_trainer import AsyncNASTrainer, SimulatedParameterServer